<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
  <channel>
    <title>标记为机器学习的活跃问题 - Thinbug</title>
    <link>https://stackoverflow.com/questions/tagged/?tagnames=machine-learning&sort=active</link>
    <description>来自 stackoverflow.com 的最新 30 个</description>
    <lastBuildDate>Sat, 16 Dec 2023 21:11:44 GMT</lastBuildDate>
    <item>
      <title>使用时间序列数据进行无监督学习？</title>
      <link>https://stackoverflow.com/questions/77672511/unsupervised-learning-with-time-series-data</link>
      <description><![CDATA[我正在处理几个月内每日汇总的用户活动数据（用户不必每天进行活动）。我正在寻找一种将相似用户聚集在一起的方法，但我有点困惑如何将时间序列数据合并到无监督学习算法中。
我对此的想法是旋转数据，以便每月的每一天都有列。然而，我觉得这会导致“维度诅咒”。所以我想知道是否有更好的方法。]]></description>
      <guid>https://stackoverflow.com/questions/77672511/unsupervised-learning-with-time-series-data</guid>
      <pubDate>Sat, 16 Dec 2023 21:07:59 GMT</pubDate>
    </item>
    <item>
      <title>为什么我使用随机森林回归器得到负 R2 分数？</title>
      <link>https://stackoverflow.com/questions/77672303/why-im-getting-a-negative-r2-score-with-random-forest-regressor</link>
      <description><![CDATA[我试图使用 Phyton 中的随机森林模型来预测 MOF 的一些变量（来自一篇科学论文），但 R2 的值为负值（与论文不同，论文为正值）。我实际上不知道问题是否出在我的数据集（涉及将数值分配给字符串）或我的代码中。原始数据集是文学数据集，我的版本是“Dados editados 3”
数据集链接：https://docs.google.com/spreadsheets/d/17r-hxcuuzEFdfsqcAdHe_9iIp1d51IvL/edit?usp=sharing&amp;ouid=111702212107777597741&amp;rtpof=true&amp;sd=true
我尝试多次检查代码，但我不知道我做错了什么，因为 RF 模型是一个非常强大的模型。此外，我还使用检测和删除异常值的函数删除数据集的所有 Nan 值。
代码：
导入 pandas 作为 pd

从 sklearn.model_selection 导入 train_test_split
从 sklearn.model_selection 导入 GridSearchCV
从 sklearn.preprocessing 导入 MinMaxScaler
从 sklearn.ensemble 导入 RandomForestRegressor
从sklearn导入预处理
从 sklearn 导入指标


将 numpy 导入为 np

将seaborn导入为sns

将 matplotlib.pyplot 导入为 plt

进口警告
warnings.filterwarnings(&#39;忽略&#39;)

从 google.colab 导入驱动器

驱动器.mount（&#39;/内容/驱动器&#39;，force_remount = True）

df = pd.read_excel(r&#39;/content/drive/My Drive/Projeto ML/Dados ML.xlsx&#39;,sheet_name =“Dados editados 3”)

打印（df.形状）

df = df.drop(columns = [&#39;酶负载&#39;, &#39;固定率&#39;, &#39;活性保留&#39;] )

df.replace(&#39;-&#39;, np.NaN, inplace = True)

df = df.dropna()

打印（df.形状）

#修改后的函数

def get_outliers(l):
    #如果保留 0.1 和 0.75，那么几乎不会过滤任何异常值
    #q1 是 0.25 分位数，q3 是 0.75 分位数
    q1 = l.分位数(0.25)
    q3 = l.分位数(0.75)
    iqr = q3-q1
    栅栏低 = q1 - 1.5 * iqr
    栅栏高 = q3 + 1.5 * iqr
    返回 [~(i&gt;=fenceLow 且 i&lt;=fenceHigh) for i in l]

离群值 = df.apply(get_outliers)

df = df[~离群值.apply(lambda x:any(x), axis=1)]


X = df.iloc[:, :-1]

Y = df.iloc[:,-1]

x_train，x_test，y_train，y_test = train_test_split（X，Y，test_size = 0.25，random_state = 42）


打印（X）

缩放器 = 预处理.MinMaxScaler(feature_range = (0.1, 0.9))

x_train = 缩放器.fit_transform(x_train)

x_test= 缩放器.fit_transform(x_test)

从 sklearn.model_selection 导入 KFold
从 sklearn.model_selection 导入 GridSearchCV
从 sklearn.model_selection 导入 cross_val_score
从 sklearn.metrics 导入 r2_score
从 matplotlib 导入 pyplot 作为 plt


rf = RandomForestRegressor()

rf.fit(x_train, y_train)

y_pred = rf.predict(x_test)


k_folds = KFold(n_splits = 6)

分数 = cross_val_score(rf, x_train, y_train, cv = k_folds, 评分 = “r2”)



print(&quot;简历分数：&quot;, 分数)
print(&quot;平均简历分数：&quot;, Scores.mean())
print(&quot;平均值中使用的 CV 分数数量：&quot;, len(scores))

在此处输入图像描述
有什么建议吗？！]]></description>
      <guid>https://stackoverflow.com/questions/77672303/why-im-getting-a-negative-r2-score-with-random-forest-regressor</guid>
      <pubDate>Sat, 16 Dec 2023 19:55:00 GMT</pubDate>
    </item>
    <item>
      <title>我没有使用下面的代码获得相应年份的子图。该怎么办？</title>
      <link>https://stackoverflow.com/questions/77672294/im-not-getting-the-sub-plots-for-the-respective-years-using-the-below-code-wha</link>
      <description><![CDATA[在此处输入图像描述weather_df[&#39;2010&#39;:&#39;2020&#39;]。 resample(&#39;D&#39;).fillna(method=&#39;pad&#39;).plot(subplots=True,Figsize=(25,25))
这些图没有图表。仅显示 x 和 y 轴，没有任何绘图。
查找代码的更正并简化代码。]]></description>
      <guid>https://stackoverflow.com/questions/77672294/im-not-getting-the-sub-plots-for-the-respective-years-using-the-below-code-wha</guid>
      <pubDate>Sat, 16 Dec 2023 19:50:52 GMT</pubDate>
    </item>
    <item>
      <title>为什么pytorch损失达到最小值时不稳定，而keras损失保持稳定？</title>
      <link>https://stackoverflow.com/questions/77672172/why-is-pytorch-loss-unstabile-when-reaching-minimum-while-keras-loss-keeps-stab</link>
      <description><![CDATA[]]></description>
      <guid>https://stackoverflow.com/questions/77672172/why-is-pytorch-loss-unstabile-when-reaching-minimum-while-keras-loss-keeps-stab</guid>
      <pubDate>Sat, 16 Dec 2023 19:12:16 GMT</pubDate>
    </item>
    <item>
      <title>如何将会话缓冲内存与提示模板连接到Gemini-pro模型</title>
      <link>https://stackoverflow.com/questions/77671882/how-to-conversational-buffer-memory-with-a-prompt-template-to-gemini-pro-model</link>
      <description><![CDATA[嗨，我正在尝试使用 Gemini-pro LLM 模型构建一个具有内存支持的对话聊天机器人
我收到此错误消息：
ChatGoogleGenerativeAIError：Gemini 不支持“系统”类型的消息。请仅向其提供人类或人工智能（用户/助理）消息。
这是我的代码：
from langchain.chains import LLMChain
从 langchain.prompts 导入 (
    聊天提示模板，
    HumanMessagePrompt模板，
    消息占位符，
    系统消息提示模板，
）
从 langchain.chains 导入 ConversationChain
从 langchain.memory 导入 ConversationBufferMemory



＃ 迅速的
提示 = 聊天提示模板(
    消息=[
        SystemMessagePromptTemplate.from_template(
            “你是一名课程推荐者，你向候选人询问几个问题，以了解他的个人兴趣、最终目标和当前技能水平，并向他提供一份精选的课程列表，并注明其难度级别为初级、中级和高级。”
        ),
        # 这里的`variable_name`必须与内存对齐
        MessagesPlaceholder(variable_name=&quot;chat_history&quot;),
        HumanMessagePromptTemplate.from_template(“{问题}”),
    ]
）

# 请注意，我们使用 `return_messages=True` 来适应 MessagesPlaceholder
# 请注意，“chat_history”与 MessagesPlaceholder 名称一致
内存 = ConversationBufferMemory(memory_key=“chat_history”, return_messages=True)
对话= LLMChain（llm=llm，提示=提示，详细=真，内存=内存）

# 请注意，我们只是传入 `question` 变量 - `chat_history` 由内存填充
对话({“问题”:“嗨”})

我试图给出系统提示，但它说 Gemini 型号不支持系统提示]]></description>
      <guid>https://stackoverflow.com/questions/77671882/how-to-conversational-buffer-memory-with-a-prompt-template-to-gemini-pro-model</guid>
      <pubDate>Sat, 16 Dec 2023 17:40:34 GMT</pubDate>
    </item>
    <item>
      <title>我应该应用什么预处理来对雕刻文本执行 OCR？</title>
      <link>https://stackoverflow.com/questions/77671624/what-preproccessing-should-i-apply-to-perform-an-ocr-on-an-engraved-text</link>
      <description><![CDATA[我正在尝试对下面有一些其他文本的雕刻数字执行 OCR（参见上图），我正在尝试读取数字并忽略黑色文本。
 , 
我尝试过谷歌ML套件文本识别，但它不起作用，我尝试过应用许多过滤器，如灰度和颜色反转，但它也不起作用。我有一些关于使用 python 和 pytesseract 进行深度学习的线索，但我几乎可以肯定这也行不通。
我想知道，这里的方法是什么？我应该对图像进行任何特定处理吗？或者这是一个机器学习问题？这是否可以解决？]]></description>
      <guid>https://stackoverflow.com/questions/77671624/what-preproccessing-should-i-apply-to-perform-an-ocr-on-an-engraved-text</guid>
      <pubDate>Sat, 16 Dec 2023 16:10:46 GMT</pubDate>
    </item>
    <item>
      <title>带有棋盘数据的简单扩散模型</title>
      <link>https://stackoverflow.com/questions/77671619/simple-diffusion-model-with-checkerboard-data</link>
      <description><![CDATA[我一直在尝试使用由点（x，y）组成的棋盘数据构建一个简单的扩散模型。所以它是二维数据。
def get_noise_level(step,total_steps,max_noise_level=1.0):
    # 定义高斯分布的均值和标准差
    平均值 = 总步数 / 2
    std_dev =total_steps/4 # 这可以根据所需的传播进行调整

    # 计算高斯噪声水平
    gaussian_noise_level = np.exp(-((步长 - 平均值) ** 2) / (2 * std_dev ** 2))

    # 将噪声级别缩放到 0 到 max_noise_level 之间
    返回 gaussian_noise_level * max_noise_level

以上是我的功能。获取噪音水平
# 模型定义
类扩散模型（nn.Module）：
    def __init__(自身):
        超级().__init__()
        self.fc1 = nn.Linear(2, 128)
        self.fc2 = nn.Linear(128, 128)
        self.fc3 = nn.Linear(128, 2)

    def 前向（自身，x）：
        x = torch.relu(self.fc1(x))
        x = torch.relu(self.fc2(x))
        返回 self.fc3(x)

以上是我的简单模型
数据集 = TensorDataset(数据)
data_loader = DataLoader(数据集,batch_size=512,shuffle=True)

模型=扩散模型()
优化器 = optim.Adam(model.parameters(), lr=0.001)

纪元数 = 10
总步数 = 200

对于范围内的纪元（num_epochs）：
    纪元损失 = 0.0
    对于 i，（批处理，）枚举（data_loader）：
        current_step = epoch * len(data_loader) + i
        噪声级别 = get_noise_level(当前步数, 总步数)
        噪声 = torch.randn_like(batch) * 噪声级别
        噪声数据 = 批次 + 噪声

        # 训练模型
        优化器.zero_grad()
        预测噪声 = 模型（噪声数据）
        损失 = nn.MSELoss()(预测噪声, 噪声)
        loss.backward()
        优化器.step()
        epoch_loss += loss.item()
        
    Average_epoch_loss = epoch_loss / len(data_loader)
    print(f&quot;历元 {epoch+1}/{num_epochs}, 损失: {average_epoch_loss:.4f}&quot;)

以上是简单的训练代码。
在这里，我观察到奇怪的损失减少：
Epoch 1/10，损失：0.2600
纪元 2/10，损失：0.0017
纪元 3/10，损失：0.0000
纪元 4/10，损失：0.0000
纪元 5/10，损失：0.0000
纪元 6/10，损失：0.0000
纪元 7/10，损失：0.0000
第 8/10 纪元，损失：0.0000
9/10 纪元，损失：0.0000
第 10/10 纪元，损失：0.0000

此外，当我尝试使用模型生成样本时，我生成的所有值都是 NaN。对这里的问题有什么想法吗？我从此处获取数据。]]></description>
      <guid>https://stackoverflow.com/questions/77671619/simple-diffusion-model-with-checkerboard-data</guid>
      <pubDate>Sat, 16 Dec 2023 16:08:49 GMT</pubDate>
    </item>
    <item>
      <title>当我尝试在 python 中使用 numpy 从头开始​​构建神经网络时出现矩阵乘法错误</title>
      <link>https://stackoverflow.com/questions/77671165/matrix-multiplication-error-when-i-tried-to-build-the-neural-network-from-scratc</link>
      <description><![CDATA[我是机器学习的初学者，当我了解神经网络的数学工作时，我尝试使用 Numpy 从头开始​​构建它。我尝试构建的神经网络结构是具有 3 个节点的 input_layer -&gt; hidden_​​layer_1 有 2 个节点 -&gt; hidden_​​layer_2 有 2 个节点 -&gt;具有 1 个节点的输出层。两个隐藏层都使用ReLu激活函数，输出层使用Sigmoid激活函数。代码如下：
将 numpy 导入为 np
将 pandas 导入为 pd

W1 = np.random.rand(2, 3) # 权重矩阵
W2 = np.random.rand(2, 2)
W3 = np.random.rand(1, 2)

B1 = np.random.rand(2, 1) # 偏差向量
B2 = np.random.rand(2, 1)
B3 = np.random.rand(1, 1)

ReLu = lambda x : np.maximum(x, 0)
S 型 = lambda x : 1/ (1+np.exp(-x))

defforward_prop（输入）：

    Z1 = W1@输入 + B1
    A1 = ReLu(Z1)
    
    Z2 = W2@A1 + B2
    A2 = ReLu(Z2)
    
    Z3 = W3@A2 + B3
    A3 = 乙状结肠(Z3)
        
    返回 Z1、A1、Z2、A2、Z3、A3

d_relu = lambda x : x&gt;0
d_sigmoid = lambda x : np.exp(-x) / (1+np.exp(-x))**2

def back_prop(Z1, A1, Z2, A2, Z3, A3, X, Y):
    
    #衍生品
    dC_dA3 = 2*A3 - 2*Y
    
    dA3_dZ3 = d_sigmoid(Z3)
    dZ3_dW3 = A2
    dZ3_dB3 = 1
    dZ3_dA2 = W3
    
    dA2_dZ2 = d_relu(Z2)
    dZ2_dW2 = A1
    dZ2_dB2 = 1
    dZ2_dA1 = W2
    
    dA1_dZ1 = d_relu(Z1)
    dZ1_dW1 = X
    dZ1_dB1 = 1
    
    dC_dW3 = dC_dA3 @ dA3_dZ3 @ dZ3_dW3.T
    dC_dB3 = dC_dA3 @ dA3_dZ3 * dZ3_dB3
    dC_dA2 = dC_dA3 @ dA3_dZ3 @ dZ3_dA2
    dC_dW2 = dC_dA2 @ dA2_dZ2 @ dZ2_dW2.T
    dC_dB2 = dC_dA2 @ dA2_dZ2 * dZ2_dB2
    dC_dA1 = dC_dA2 @ dA2_dZ2 @ dZ2_dA1 # 问题就在这里
    dC_dW1 = dC_dA1 @ dA1_dZ1 @ dZ1_dW1.T
    dC_dB1 = dC_dA1 @ dA1_dZ1 * dZ1_dB1
    
    返回 dC_dW1、dC_dB1、dC_dW2、dC_dB2、dC_dW3、dC_dB3

数据 = pd.read_csv(&#39;light_dark_font_training_set.csv&#39;)
x = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=1/3)

n = x_train.shape[0]
L = 0.05
纪元 = 100_000

对于范围内的 i（纪元）：

    idx = np.random.choice(n, 1, 替换=False)
    x_sample = x_train[idx].transpose()
    y_样本 = y_train[idx]
    
    z1、a1、z2、a2、z3、a3 =forward_prop(x_sample)
    w1, b1, w2, b2, w3, b3 = back_prop(z1, a1, z2, a2, z3, a3, x_sample, y_sample)
    
    W1 -= 长*w1
    W2 -= 长*w2
    W3 -= 长*w3
    
    B1 -= L*b1
    B2 -= L*b2
    B3 -= L*b3
    
    如果 i%10000 == 0:
        打印（一）

当我尝试运行上述程序时，它显示以下值错误，这表明矩阵维度与矩阵乘法不匹配。起初，我以为反向传播中的偏导数存在一些问题，但就我的知识而言，它对我来说看起来很好。我不知道为什么会发生这种情况。如果有人解决并解释这个问题那就太好了。
&lt;前&gt;&lt;代码&gt;-------------------------------------------------------- -------------------------------------------
ValueError Traceback（最近一次调用最后一次）
 中的 ~\AppData\Local\Temp/ipykernel_11036/3060626554.py
      6
      7 z1, a1, z2, a2, z3, a3 =forward_prop(x_sample)
----&gt; 8 w1, b1, w2, b2, w3, b3 = back_prop(z1, a1, z2, a2, z3, a3, x_sample, y_sample)
      9
     10 W1 -= 长*w1

~\AppData\Local\Temp/ipykernel_11036/566612658.py in back_prop(Z1, A1, Z2, A2, Z3, A3, X, Y)
     22 dC_dW2 = dC_dA2 @ dA2_dZ2 @ dZ2_dW2.T
     23 dC_dB2 = dC_dA2 @ dA2_dZ2 * dZ2_dB2
---&gt; 24 dC_dA1 = dC_dA2 @ dA2_dZ2 @ dZ2_dA1#问题就在这里
     25 dC_dW1 = dC_dA1 @ dA1_dZ1 @ dZ1_dW1.T
     26 dC_dB1 = dC_dA1 @ dA1_dZ1 * dZ1_dB1

ValueError: matmul: 输入操作数 1 的核心维度 0 不匹配，gufunc 签名为 (n?,k),(k,m?)-&gt;(n?,m?)（大小 2 与 1 不同）
]]></description>
      <guid>https://stackoverflow.com/questions/77671165/matrix-multiplication-error-when-i-tried-to-build-the-neural-network-from-scratc</guid>
      <pubDate>Sat, 16 Dec 2023 13:56:10 GMT</pubDate>
    </item>
    <item>
      <title>有没有办法在 python 中将 pycuber 对象显示到 GUI 上[关闭]</title>
      <link>https://stackoverflow.com/questions/77670947/is-there-a-way-to-display-an-object-of-pycuber-onto-a-gui-in-python</link>
      <description><![CDATA[我正在编写一个机器学习模型，它读取用户给出的魔方并给出解决方案。为了解决这个问题，我使用了一个名为 Pycuber 的模块，它可以移动到当前的多维数据集。我已经完成了模型训练和测试，但现在我只能在终端中显示它，我想在 GUI 上显示它，但我找不到任何资源来帮助我。请帮忙。
我尝试过使用 Tkinter 和 Opencv，但由于某种原因它永远不会打印在框架上，我什至尝试过使用 ursina 库，但都失败了。]]></description>
      <guid>https://stackoverflow.com/questions/77670947/is-there-a-way-to-display-an-object-of-pycuber-onto-a-gui-in-python</guid>
      <pubDate>Sat, 16 Dec 2023 12:44:56 GMT</pubDate>
    </item>
    <item>
      <title>我需要手背静脉认证系统的数据集？ [关闭]</title>
      <link>https://stackoverflow.com/questions/77669704/i-need-a-dataset-for-dorsal-hand-vein-authentication-system</link>
      <description><![CDATA[我需要一个灰度手背静脉数据集
我发现一张只有 32 张图片，我需要一张更大的图片
，我的项目也是手背静脉认证系统，有谁知道如何在Python中实现它的代码以及使用什么算法我应用了clahe然后自适应阈值和形态学操作
之后我计算黑色像素，但结果是错误的用户 0 右手像素计数更接近另一只手的左手像素计数，下一步是什么或我可以做什么来解决这个问题？]]></description>
      <guid>https://stackoverflow.com/questions/77669704/i-need-a-dataset-for-dorsal-hand-vein-authentication-system</guid>
      <pubDate>Sat, 16 Dec 2023 03:21:04 GMT</pubDate>
    </item>
    <item>
      <title>未找到数据集..缺少路径..训练模型时[关闭]</title>
      <link>https://stackoverflow.com/questions/77668769/dataset-not-found-missing-path-while-training-the-model</link>
      <description><![CDATA[我收到此错误：
Ultralytics YOLOv8.0.227 🚀 Python-3.11.5 torch-2.1.2+cpu CPU（第 13 代 Intel Core(TM) i7-13700K）
引擎\训练器：任务=检测、模式=训练、模型=yolov8s.pt、数据=data/data.yaml、epochs=100、耐心=50、批次=16、imgsz=640、save=True、save_period=-1 ，缓存=假，设备=无，工人= 2，项目=无，名称= train10，exist_ok =假，预训练=真，优化器=自动，详细=真，种子= 0，确定性=真，single_cls =假，矩形=False、cos_lr=False、close_mosaic=10、resume=False、amp=True、fraction=1.0、profile=False、freeze=None、overlap_mask=True、mask_ratio=4、dropout=0.0、val=True、split=val 、 save_json=False、save_hybrid=False、conf=None、iou=0.7、max_det=300、half=False、dnn=False、plots=True、source=None、vid_stride=1、stream_buffer=False、visualize=False、augment =False、agnostic_nms=False、classes=None、retina_masks=False、show=False、save_frames=False、save_txt=False、save_conf=False、save_crop=False、show_labels=True、show_conf=True、show_boxes=True、line_width=None 、format=torchscript、keras=False、optimize=False、int8=False、dynamic=False、simple=False、opset=None、workspace=4、nms=False、lr0=0.01、lrf=0.01、动量=0.937、weight_decay =0.0005，warmup_epochs=3.0，warmup_momentum=0.8，warmup_bias_lr=0.1，box=7.5，cls=0.5，dfl=1.5，pose=12.0，kobj=1.0，label_smoothing=0.0，nbs=64，hsv_h=0.015，hsv_s=0.7 ，hsv_v=0.4，度=0.0，平移=0.1，比例=0.5，剪切=0.0，透视=0.0，flipud=0.0，fliplr=0.5，马赛克=1.0，mixup=0.0，copy_paste=0.0，cfg=无，跟踪器=botsort.yaml, save_dir=runs\detect\train10
-------------------------------------------------- ------------------------
FileNotFoundError Traceback（最近一次调用最后一次）
文件 ~\anaconda3\Lib\site-packages\ultralytics\engine\trainer.py:116，在 BaseTrainer.__init__(self, cfg, overrides, _callbacks)
    115 (&#39;yaml&#39;, &#39;yml&#39;) 中的 elif self.args.data.split(&#39;.&#39;)[-1] 或 (&#39;检测&#39;, &#39;分段&#39;, &#39;姿势&#39;) 中的 self.args.task:
--&gt; 116 self.data = check_det_dataset（self.args.data）
    117 如果 self.data 中的“yaml_file”：

文件 ~\anaconda3\Lib\site-packages\ultralytics\data\utils.py:253，在 check_det_dataset（数据集，自动下载）中
    第238章
    239 如果本地找不到数据集，请下载、验证和/或解压缩数据集。
    240
   （...）
    250（dict）：解析的数据集信息和路径。
    第251章
--&gt; 253 file = check_file（数据集）
    255#下载（可选）

文件~\anaconda3\Lib\site-packages\ultralytics\utils\checks.py:460，在check_file(文件、后缀、下载、硬)
    第459章
--&gt; 460 raise FileNotFoundError(f“‘{file}’不存在”)
    [第 461 章] 1、硬：

FileNotFoundError：“data/data.yaml”不存在

上述异常是导致以下异常的直接原因：

RuntimeError Traceback（最近一次调用最后一次）
第 7 行 [25] 中的单元格
      4 model = YOLO(&#39;yolov8s.pt&#39;) # 加载预训练模型（推荐用于训练）
      6 # 训练模型
----&gt; 7 个结果 = model.train(data=&#39;data/data.yaml&#39;, epochs=100, imgsz=640, Workers=2)

文件 ~\anaconda3\Lib\site-packages\ultralytics\engine\model.py:333，在 Model.train(self, trainer, **kwargs)
    第330章
    第331章
--&gt;第333章
    第334章
    第335章

文件 ~\anaconda3\Lib\site-packages\ultralytics\engine\trainer.py:120，在 BaseTrainer.__init__(self, cfg, overrides, _callbacks)
    118 self.args.data = self.data[&#39;yaml_file&#39;] #用于验证&#39;yolo train data=url.zip&#39;用法
    119 异常如 e 除外：
--&gt; 120 从 e 引发 RuntimeError(emojis(f&quot;Dataset &#39;{clean_url(self.args.data)}&#39; error ❌ {e}&quot;))
    122 self.trainset，self.testset = self.get_dataset（self.data）
    第123章

RuntimeError：数据集“data/data.yaml”错误“data/data.yaml”不存在

​
从 ultralytics 导入 YOLO

# 加载模型
model = YOLO(&#39;yolov8s.pt&#39;) # 加载预训练模型（推荐用于训练）

# 训练模型
结果= model.train(data=&#39;data/data.yaml&#39;,epochs=100,imgsz=640,workers=2)

这就是我通过 jupyter 进行的操作]]></description>
      <guid>https://stackoverflow.com/questions/77668769/dataset-not-found-missing-path-while-training-the-model</guid>
      <pubDate>Fri, 15 Dec 2023 20:51:38 GMT</pubDate>
    </item>
    <item>
      <title>定制训练的 yolov7 模型准确率为 95%，但几乎可以检测到所有内容，但不能检测到我想在网络摄像头上检测到的对象 [关闭]</title>
      <link>https://stackoverflow.com/questions/77667354/custom-trained-yolov7-model-is-95-percent-accurate-but-detects-almost-everything</link>
      <description><![CDATA[使用 cuda 在 VS Code 中使用 yolov7 训练模型。我使用了一个预先标记的数据集，我认识的人已经成功地完成了与我相同的任务。我使用 500 张图像对模型进行了 1000 个时期的训练。在图表中，模型是准确的，但是当我用网络摄像头测试它时，它检测到所有东西就像汽水罐一样（我正在尝试检测汽水罐）。但是当我向它展示一个汽水罐时，它不会检测到它，但它会像汽水罐一样检测到我的脸、墙壁、冰箱。
问题是，我将包含模型的文件夹发送给了我的程序员朋友。在他的计算机上，该模型运行良好并且正在检测汽水罐。是否有原因导致该模型在他的电脑上运行良好但在我的电脑上运行不佳？]]></description>
      <guid>https://stackoverflow.com/questions/77667354/custom-trained-yolov7-model-is-95-percent-accurate-but-detects-almost-everything</guid>
      <pubDate>Fri, 15 Dec 2023 15:45:07 GMT</pubDate>
    </item>
    <item>
      <title>大数据集的线性回归[关闭]</title>
      <link>https://stackoverflow.com/questions/77662894/linear-regression-on-large-dataset</link>
      <description><![CDATA[我正在编写一个使用预先训练的神经网络从图像中提取特征的代码。
然后使用线性回归模型训练所有图像的组合特征。
问题是提取的特征非常大，而且我们有一个很大的数据集。因此，由于内存问题，加载整个 features.csv 是不可能的。
解决这个问题的潜在方法是什么？
我尝试了增量PCA，但即使如此，我也需要先加载整个数据集，然后它会执行批量PCA（如果我没记错的话）]]></description>
      <guid>https://stackoverflow.com/questions/77662894/linear-regression-on-large-dataset</guid>
      <pubDate>Thu, 14 Dec 2023 20:26:38 GMT</pubDate>
    </item>
    <item>
      <title>RuntimeError：预期 4 维权重 [32, 2048, 5, 5] 的 4 维输入，但得到了大小 [10, 136] 的 2 维输入[关闭]</title>
      <link>https://stackoverflow.com/questions/77662813/runtimeerror-expected-4-dimensional-input-for-4-dimensional-weight-32-2048-5</link>
      <description><![CDATA[运行时错误: 预期的 4 维输入为 4 维权重 [32, 2048, 5, 5]，但却得到了大小为 [10, 136] 的 2 维输入
请解决代码的运行时错误
;在&lt;模块&gt;中
      1#调用上面的函数
      2 # 返回：测试图像、测试预测关键点、测试地面真实关键点
----&gt; 3 test_images、test_outputs、gt_pts = net_sample_output()
      4
      5 # 打印出数据的维度，看看它们是否有意义

&lt;ipython-input-23-dcd307a0f805&gt;在 net_sample_output() 中
     14
     15 # 前向传递以获得净输出
---&gt; 16 output_pts = net(图像)
     17 号
     18 # 重塑为batch_size x 68 x 2 pts

_call_impl 中的 ~/miniconda3/envs/cv-nd/lib/python3.6/site-packages/torch/nn/modules/module.py(self, *input, **kwargs)
   第1100章
   第1101章
-&gt;第1102章
   第1103章
   第1104章

〜/Documents/GitHub/P1_Facial_Keypoints/models.py 向前（自我，x）
     54 ## TODO：定义该模型的前馈行为
...
--&gt;第443章
    第444章
    [第 445 章]张量：

RuntimeError: 预期 4 维输入为 4 维权重 [32, 2048, 5, 5]，但得到了大小为 [10, 136] 的 2 维输入

&lt;前&gt;&lt;代码&gt;]]></description>
      <guid>https://stackoverflow.com/questions/77662813/runtimeerror-expected-4-dimensional-input-for-4-dimensional-weight-32-2048-5</guid>
      <pubDate>Thu, 14 Dec 2023 20:08:11 GMT</pubDate>
    </item>
    <item>
      <title>随机森林分类器演示期间用户输入的问题</title>
      <link>https://stackoverflow.com/questions/77653884/a-problem-with-the-user-input-during-the-random-forest-classifier-demonstration</link>
      <description><![CDATA[我使用随机森林分类器获得了超过 90% 的准确率，但我担心其余算法给出的结果要低得多：
指标 
但这不是主要问题。问题是，当我使用用户输入时，预测是 100% 错误的。用户输入的列的顺序对应于训练数据集列的位置。
模型 = RandomForestClassifier()
model.fit(X_train, y_train)
预测 = model.predict(X_test)
acc = precision_score(y_test, 预测) # 输出：0.91

X_test_user = df_user_compounds_1.to_numpy()
user_input_predictions_1 = model.predict(X_test_user) #
user_input_predictions_1 # 输出： array([0, 0, 0, 0, 0], dtype=int64)，但应该是： array([1, 1, 1, 1, 1],dtype=int64)

有人知道为什么会发生这种情况吗？
数据集经过预处理 - 没有缺失值，没有重复，使用 RandomOverSampler 进行平衡，使用 MinMaxScaler 进行缩放，没有负值，并且包含 11 个特征/7K 行。
……
非常感谢@ElvinJafarov。这些是来自 df_user_compounds_1 的部分，以及根据您的建议生成的 X_test。

由于我已经使用了 MinMaxScaler()，因此我必须向 df_user_compounds_1 添加另外两行，其中包含相应的最小值和最大值，以模拟与原始缩放相同的缩放。我通过 df.describe(include=“all”) 找到了最大值和最小值，将这两行连接到用户输入数据帧并缩放 
我对结果很满意：前 5 个必须是 1，即 5 个中的 4 个 &lt; img alt=&quot;结果&quot; src=&quot;https://i.stack.imgur.com/WssFz.png&quot; /&gt;]]></description>
      <guid>https://stackoverflow.com/questions/77653884/a-problem-with-the-user-input-during-the-random-forest-classifier-demonstration</guid>
      <pubDate>Wed, 13 Dec 2023 13:17:28 GMT</pubDate>
    </item>
    </channel>
</rss>